# Generated by Django 4.1.1 on 2023-08-14 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('link', models.URLField()),
                ('image', models.URLField()),
                ('source', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Financial News',
            },
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NamedEntityRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('explanation', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='named_entity_recognition', to='classify_news.financialnews')),
            ],
        ),
        migrations.CreateModel(
            name='ClassifiedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_integer', models.IntegerField()),
                ('accuracy_percentage', models.IntegerField(null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classify_news', to='classify_news.financialnews')),
                ('sentiment_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classify_news', to='classify_news.sentiment')),
            ],
            options={
                'verbose_name_plural': 'Classified News',
            },
        ),
    ]
