# Generated by Django 4.1.1 on 2023-08-14 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiednews',
            name='sentiment_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classify_sentiment', to='classify_news.sentiment'),
        ),
    ]
